version: '2'
services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    stdin_open: true
    container_name: frontend
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend
    restart: always
    build: backend
    ports:
      - 1986:1986
    expose: 
      - 1986